apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: notes
      layer: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: notes
        layer: frontend
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/agile-terra-359116/notes-app-repo/notes-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pg-connection-url
                  key: DATABASE_URL
      imagePullSecrets:
        - name: default-secret

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - name: service-clusterip
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: notes
    layer: frontend
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vote-api
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: notesapp-external-ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
